# Generated by Django 4.2.7 on 2023-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("email_address", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("year_of_birth", models.IntegerField()),
                ("phone_number", models.CharField(max_length=15)),
                ("email_address", models.EmailField(max_length=254)),
                ("country", models.CharField(default="Kenya", max_length=50)),
                ("county", models.CharField(max_length=50)),
                ("sub_county", models.CharField(max_length=50)),
            ],
        ),
    ]
