# Generated by Django 4.2.6 on 2023-11-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membersmgmt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
